### ISSUE TITLE
Automated tracking workflow isn't available despite having installed CPLEX Optimization studio 12.7

### ISSUE THREAD

**Issue by JoaoFirmino** [ilastik/ilastik#1403]
Hi there,

I am trying to use your automated tracking workflow but after having installed CPLEX Optimization Studio 12.7 (the IBM website does not show the 12.5.1 version you mention in your guide!), ilastik still does not show this option in its menu. 
I followed your troubleshooting guide and troubleshooted as much as I could (I consider myself to be a complete beginner in programming), but it still does not work...
No error messages appear - I just do not have the automated tracking workflow option in the menu. I am running ilastik 1.2.0rc10.
Could you help me out?

Thanks a lot and happy New Year,

Joao Firmino

**Comment by stuarteberg** [comment]
We released a new version on Dec 21.  In theory, it should work even without CPLEX.  Can you give it a try?  If it doesn't work, please let me know what OS you're using.
http://ilastik.org/download

**Comment by JoaoFirmino** [comment]
Hi there,

It still does not show that option in the menu - I am running Windows 10 
Education - version 1511 build 10586.713

Thanks for the quick reply,

Joao

**Comment by stuarteberg** [comment]
OK, thanks for the update.  Our tracking and Windows experts are not available today.  I think we won't be able to resolve this until next week.

**Comment by JoaoFirmino** [comment]
No worries.

I can wait for their feedback next week.

Thanks a lot once again for the quick reply,

Best,

Joao

**Comment by ilastikdev** [comment]
Hi Firminio,

For Automated Tracking and Tracking with Learning
in ilastik 1.2.x version on Windows
you will need Cplex 12.6.3

Janez.














Quoting Joao Firmino <notifications@github.com>:

**Comment by JoaoFirmino** [comment]
Hi Janez,

Unfortunately the only version of CPLEX you can get on the IBM website 
is the 12.7. What can I do?

Thanks a lot,

Joao

**Comment by ilastikdev** [comment]
Use this as a starting point:

http://www-01.ibm.com/support/docview.wss?uid=swg24041278

Janez









Quoting Joao Firmino <notifications@github.com>:

**Comment by JoaoFirmino** [comment]
I tried your website but it still does not allow me to download that 
software - I used my ibm id but the site states that the CPLEX 12.6.3 
links are not active anymore...

Once again, you can only obtain version 12.7 of the software...

Joao

**Comment by ilastikdev** [comment]
Hi Firminio,

We will add support for cplex 12.7 in a new release (this month).

In the mean time linux and mac versions of ilastik do run automated  
tracking with a flow solver that needs no cplex.

Janez.





Quoting Joao Firmino <notifications@github.com>:

**Comment by ilastikdev** [comment]
Hi Firmino,

Depending on the size of your project you may also be able to use this  
version of 12.6.3:


https://www-01.ibm.com/marketing/iwm/tnd/preconfig.jsp?id=2016-03-23+06%3A13%3A56.049452R&S_TACT=&S_CMP=

If your project is to big then you could first get accustomed to the  
pipeline on a small crop from your data.

Janez.




Quoting Joao Firmino <notifications@github.com>:

**Comment by stuarteberg** [comment]
Side note for tracking devs and mac users (@ilastikdev, @chaubold, @JaimeIvanCervantes, @Steffen-Wolf):

>We will add support for cplex 12.7 in a new release (this month).

We can't upgrade to CPLEX 12.7 without making some significant changes to our macOS build scripts.  That's because CPLEX **finally** links against `libc++.dylib` instead of apple's ancient version of `libstdc++.dylib`.

The good news is that I wanted to make those build script changes anyway.  It shouldn't be too hard, and upgrading all of our recipes to use `libc++` will have many other benefits.  I'm working on it right now.

**Comment by chaubold** [comment]
@stuarteberg: Thanks for the heads-up. But... The dependencies that we do not build ourselves (=those we take from conda) are still built with Apple's old GCC 4.2 version and hence link against `libstdc++` of that GCC version, right? Are there any locations where this might cause problems (as e.g. passing a `std::string` from one of our `libc++`-linked libraries to a `libstdc++`-linked library that we take from conda)?

I remember I spent quite some time trying to use both `libc++` and `libstdc++` in *buildem*, just to notice bug after bug because a lot of these problems only show up at runtime.

The IBM guys weren't so nice to ship both, a `libc++` and a `libstdc++` version as Gurobi does?

**Comment by stuarteberg** [comment]
>The dependencies that we do not build ourselves (=those we take from conda) are still built with Apple's old GCC 4.2 version and hence link against libstdc++ of that GCC version, right?

Yes.  But conda-forge now uses `clang` and `libc++` for their stack, so I'm investigating the possibility of switching to using the `conda-forge` channel instead of `defaults` for many packages.

>The IBM guys weren't so nice to ship both, a libc++ and a libstdc++ version as Gurobi does?

As far as I can tell, no.

**Comment by DillonCislo** [comment]
Hi Everyone,

I hope I am writing this in the correct place - I felt as though I probably should not start an entirely new thread with the exact same title.  I am experiencing a similar issue.
I am running ilastik-1.2.0-Linux on Ubuntu 16.10 (64 bit).  I have CPLEX v12.7 installed and have successfully transferred the required .so files to the /lib/ directory of my ilastik installation as per the instructions on the automatic tracking web page.  However upon start up my ilastik start screen does not display an option for an Automatic Tracking workflow 
![image](https://cloud.githubusercontent.com/assets/20879110/22858695/2d8e1eba-f079-11e6-9c74-4abb04bf297d.png)

At first I thought this was an issue with my CPLEX installation, but this is absolutely running properly on its own.  Additionally, judging from your comments in this thread it seems as though CPLEX is not even necessary for running the Automatic Tracking workflow on Linux.  Please let me know if there's any insight you can offer-I am very much hoping to incorporate this workflow into my research and would very much like to resolve this issue.

**Comment by chaubold** [comment]
@DillonCislo: good to hear that it was just the name change 😄 .

**Comment by kkimatx89** [comment]
Hi, has there been any updates to support CPLEX 12.7 or higher versions?
I am coming across the same issues where I can't download older 12.63 version.

**Comment by chaubold** [comment]
We are currently upgrading all our dependencies, which means also using CPLEX 12.7. But unfortunately it will takes quite some time to make sure that we do not break anything by the change before we can release the next version of ilastik. 

In the meantime you should be able to use the heuristic tracking solver on linux and OSX. Windows users will unfortunately have to wait until our update is done. Sorry.

**Comment by ricaliari** [comment]
I am having exactly the same issue. Any news?

**Comment by jbychang** [comment]
Hi folks,

I'm interested in using the cell tracking function, and I also haven't been able to obtain the version of CPLEX required by the current ilastik release.

Best,
Jeremy

**Comment by chaubold** [comment]
Sorry, we have built most of our (around 15) C++ dependencies for windows but are still debugging some runtime errors. This will still take some time (I guess a month, as this is not the only thing we're working on). Until then, please use the Linux or Mac binaries if you have a machine with those operating systems available.

**Comment by jbychang** [comment]
Ok, thanks for the note.

**Comment by surjeets** [comment]
Hi!
I was wondering if the updated version that is compatible with CPLEX 12.7 on windows is available now ?

**Comment by jbychang** [comment]
In the end, I was able to get in touch with the Academic Initiative at IBM, and they linked me to the older version of CPLEX. Perhaps they can help you as well.

**Comment by k-dominik** [comment]
Hey @surjeets, thank you for letting us know!

**Comment by chaubold** [comment]
Good to know that IBM does hand out the old CPLEX version on request! Thanks.

The other good news is that we're working hard to get a beta release of ilastik out by the end of this week which will support CPLEX 12.7 on all platforms, but also allows for running tracking without CPLEX at all.

**Comment by surjeets** [comment]
Thanks for the immediate response every one. It works great on Linux, I just installed it with CPLEX 12.7 and couldn't resist to track my animals 
![export_t 481](https://user-images.githubusercontent.com/11226511/32536505-f63e71cc-c41b-11e7-81ea-0f37abf5e148.png)

**Comment by ricaliari** [comment]
Hey @jbychang , could you let us know whom did you contact? I've tried to get in touch with them as well but with no success so far. It would be really cool to get it working :-)

**Comment by jbychang** [comment]
Sorry for the slow response, I was out of town. I think, but I am not certain, that I used the following form:

https://ibm.onthehub.com/WebStore/Support/RequestCustomerSupport.aspx

I received a response from someone with "aimember@us.ibm.com" in the signature line. If you'd like the direct email of the person who helped me, let me know. It seems a bit impolite to directly post it online.

Best,
Jeremy

**Comment by ricaliari** [comment]
Thanks Jeremy, I will contact them!

cheers,

**Comment by chaubold** [comment]
Or, you go to http://ilastik.org/download.html and grab the new ilastik beta which I _finally_ uploaded a few minutes ago 😅.

We do not require CPLEX any more for tracking, but you can use it as alternative solver and for some additional functionality. This beta version only works with CPLEX 12.7 or Gurobi 7.5 though!

**Comment by chaubold** [comment]
I'm closing this thread for now. Please reopen if it doesn't work for any of you!
