### ISSUE TITLE
Feature matrix contains NaNs (when using fastfilters)

### ISSUE THREAD

**Issue by wolfgangkeil** [ilastik/ilastik#1477]
Hey,

I am using ilastik 1.2.0 (downloaded on 04/17/2017) on Ubuntu 16.04.2 LTS.
I can start a pixel classification project, select an h5-file (z-stack with doubles in it) and select some features and add some labels. Then I start training and whenever I hit 'live update' I get an error window with the following message: 

```
Precondition violation!
RandomForest(): Feature matrix contains NaNs
(/miniconda/conda-bld/vigra_1481049025863/work/include/vigra/random_forest/rf_preprocessing.hxx:182)
 (Advanced information about this error may be found in the log file: /home/wolfgang/ilastik_log.txt)
```

After pressing OK, Ilastik will stop classification at 80% progress and not do anything further. It will allow me to continue training but after each training step, the error window keeps popping up. 
I am pretty sure the h5-file doesn't contain any NaNs. I am creating these files with Matlab h5create and h5write and I checked that there are no NaNs in the arrays before doing that. 

I've added my logfile to the bug report. 

Swift help would be greatly appreciated! 

[ilastik_log.txt](https://github.com/ilastik/ilastik/files/945758/ilastik_log.txt)

**Comment by stuarteberg** [comment]
I'm not sure what is causing this error, but I have two suggestions to help us debug it:

1. We just released ilastik-1.2.1.  Can you give that a try and see if the error still occurs in that version?

2. If that doesn't fix the problem, please open the following file:

```
ilastik-1.2.1-Linux/ilastik-meta/lazyflow/lazyflow/operators/vigraOperators.py
```

and [edit these lines](https://github.com/ilastik/lazyflow/blob/master/lazyflow/operators/vigraOperators.py#L49-L50) to look like this:

```python
    ##import fastfilters
    WITH_FAST_FILTERS = False
```

(Comment out the first line and change the second to say `False`.)

**Comment by wolfgangkeil** [comment]
I tried upgrading to 1.2.1 but that didn’t fix the issue. Editing the lines you suggested fixed it.
Thanks!

PS: Just FYI: Before editing these lines, I also tried loading tiffs of various formats and sizes as dataset to see whether it was a problem with the h5-files but the same issue occured.


Am 20.04.2017 um 21:29 schrieb Stuart Berg <notifications@github.com<mailto:notifications@github.com>>:


I'm not sure what is causing this error, but I have two suggestions to help us debug it:

  1.  We just released ilastik-1.2.1. Can you give that a try and see if the error still occurs in that version?

  2.  If that doesn't fix the problem, please open the following file:

ilastik-1.2.1-Linux/ilastik-meta/lazyflow/lazyflow/operators/vigraOperators.py


and edit these lines<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_ilastik_lazyflow_blob_master_lazyflow_operators_vigraOperators.py-23L49-2DL50&d=DwMFaQ&c=JeTkUgVztGMmhKYjxsy2rfoWYibK1YmxXez1G3oNStg&r=sk6Lt0KduiYUM10kYJxwWn0FWoRg7gwiVp9jMqbL_8I&m=jMhExV3p01M1ZyzLcMh6pDiWeRewGg1j4A57WtYOdxU&s=mWZXNLUpWNJifCmzLwkSRnqPkqSBsleACzC4TxKQtOU&e=> to look like this:

    ##import fastfilters
    WITH_FAST_FILTERS = False

(Comment out the first line and change the second to say False.)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_ilastik_ilastik_issues_1477-23issuecomment-2D296004009&d=DwMFaQ&c=JeTkUgVztGMmhKYjxsy2rfoWYibK1YmxXez1G3oNStg&r=sk6Lt0KduiYUM10kYJxwWn0FWoRg7gwiVp9jMqbL_8I&m=jMhExV3p01M1ZyzLcMh6pDiWeRewGg1j4A57WtYOdxU&s=0GbBpBQJNYoMz0NjEsNYeTj4xXEZ2nu72ODiy9UQyVI&e=>, or mute the thread<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AVTCMta2UCllfjGem2VJ2RYqQw9BrIjZks5ryAaGgaJpZM4NDtsA&d=DwMFaQ&c=JeTkUgVztGMmhKYjxsy2rfoWYibK1YmxXez1G3oNStg&r=sk6Lt0KduiYUM10kYJxwWn0FWoRg7gwiVp9jMqbL_8I&m=jMhExV3p01M1ZyzLcMh6pDiWeRewGg1j4A57WtYOdxU&s=CBlqHrdluy1I-jqinyg2Q_GzVL9IWLF_B8UVGkg2AOM&e=>.

-----------------------------------------
Wolfgang Keil
Center for Studies in Physics and Biology
The Rockefeller University, New York City

wkeil@mail.rockefeller.edu<mailto:wkeil@mail.rockefeller.edu>
+1 646 247 6660
-----------------------------------------

**Comment by stuarteberg** [comment]
@svenpeter42, Apparently, this user found a case in which `fastfilters` produces `NaN` values, but `vigra` does not.  Do you know why that might be?

@wolfgangkeil Would you mind sending us an example image to help us reproduce the problem?

**Comment by svenpeter42** [comment]
Could be -ffast-math hitting some edge case or doing some weird optimisation that's not exactly standard compliant that results in a NaN. That's a blind guess though - without an example to reproduce this problem I won't be able to help.

**Comment by stuarteberg** [comment]
@wolfgangkeil Would you mind sending us an example image to help us reproduce the problem?

**Comment by wolfgangkeil** [comment]
Dear Stuart,


Please find a link to an h5-stack here:


https://elf.rockefeller.edu/g/47c8a6c232283e202345c36a6bf7dd77/4446


I add it as training data set. Activated all features, added two labels and started training. Upon clicking on live update, the error appeared.


Also, I recently came across the same error when opening a .tiff file. Just renaming it to .tif fixed it.

Maybe that helps?


Best,

Wolfgang

**Comment by stuarteberg** [comment]
@wolfgangkeil What are the dimensions of that file? (time,channels,x,y,z)

**Comment by wolfgangkeil** [comment]
Just realized that I might have sent you the wrong h5-file.

Try this one instead:

https://elf.rockefeller.edu/g/7cc4a5ec46085ffb91f68e542bc75a7b/1798



It's (37, 192, 1393) (zyx), a single channel, single time frame. float64.

I am able to open it in Fiji, using the hdf5 plugin


Best,

Wolf



________________________________

**Comment by stuarteberg** [comment]
Thanks, @wolfgangkeil, I'm able to reproduce the problem using your example file.

**Comment by wolfgangkeil** [comment]
Let me know when it’s fixed. I’d be happy to download a newer Ilastik version and try it!
Thanks for your swift support!

W.

Am 27.04.2017 um 16:53 schrieb Stuart Berg <notifications@github.com<mailto:notifications@github.com>>:


Thanks, @wolfgangkeil<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_wolfgangkeil&d=DwMCaQ&c=JeTkUgVztGMmhKYjxsy2rfoWYibK1YmxXez1G3oNStg&r=sk6Lt0KduiYUM10kYJxwWn0FWoRg7gwiVp9jMqbL_8I&m=HQlEPiwuMlEuwv3OJv8TVtbKZ7OEVOnNB4AaBJUU_Es&s=-fN_gzpgdLgbovNJE0WDCXmJ2ZQ2SErSGjIbJ8lWO3I&e=>, I'm able to reproduce the problem using your example file.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_ilastik_ilastik_issues_1477-23issuecomment-2D297836144&d=DwMCaQ&c=JeTkUgVztGMmhKYjxsy2rfoWYibK1YmxXez1G3oNStg&r=sk6Lt0KduiYUM10kYJxwWn0FWoRg7gwiVp9jMqbL_8I&m=HQlEPiwuMlEuwv3OJv8TVtbKZ7OEVOnNB4AaBJUU_Es&s=C0AnBMfUZAzf1fHQAyVOPkcZTxGCySoRYnm93l9KmQ8&e=>, or mute the thread<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AVTCMiKrarRPpjBNyOmjxak-5FMZ26f4dCks5r0QA4gaJpZM4NDtsA&d=DwMCaQ&c=JeTkUgVztGMmhKYjxsy2rfoWYibK1YmxXez1G3oNStg&r=sk6Lt0KduiYUM10kYJxwWn0FWoRg7gwiVp9jMqbL_8I&m=HQlEPiwuMlEuwv3OJv8TVtbKZ7OEVOnNB4AaBJUU_Es&s=vKiB3wcOIXtCuOTAPJn3fCTEOEuvh-lJ_skL1iR3DyQ&e=>.

-----------------------------------------
Wolfgang Keil
Center for Studies in Physics and Biology
The Rockefeller University, New York City

wkeil@mail.rockefeller.edu<mailto:wkeil@mail.rockefeller.edu>
+1 646 247 6660
-----------------------------------------

**Comment by stuarteberg** [comment]
@svenpeter42: I did a little experimentation and found that the crash only occurs using the StructureTensorEigenvalue feature, and only for some sigmas.

I extracted a tiny cutout of the example volume:
[volume-8_17_7_1.npy.zip](https://github.com/ilastik/ilastik/files/962863/volume-8_17_7_1.npy.zip)

(That was one of the volumes that was extracted by ilastik during training.)

Indeed, `fastfilters.structureTensorEigenvalues()` does produce `NaN` values:

```python
In [16]: import numpy as np

In [17]: import vigra

In [18]: import fastfilters

In [19]: fastfilters.__version__
Out[19]: u'0.2.4-3-g198bf8a'

In [20]: image = np.load('/tmp/volume-8_17_7_1.npy')

In [21]: image = vigra.taggedView(image, 'zyxc')

In [22]: filtered = fastfilters.structureTensorEigenvalues(image, 1.0, 0.5, 2)

In [23]: np.isnan(filtered).any()
Out[23]: True
```

Looking at the location of the `NaN` values, I see no obvious pattern.  Here are a few sample slices (zoomed in).  White pixels indicate the location of `NaN` output from `structureTensorEigenvalues()`.  One noteworthy observation: All channels of the output have `NaN` at the exact same coordinates.

![screen shot 2017-04-27 at 4 49 45 pm](https://cloud.githubusercontent.com/assets/1655821/25503801/94d6f1c0-2b69-11e7-8015-9a9c033be000.png)

![screen shot 2017-04-27 at 4 48 29 pm](https://cloud.githubusercontent.com/assets/1655821/25503731/5f00bb58-2b69-11e7-9dae-a72931196b62.png)

Do the above parameter values look OK to you?  Am I violating any preconditions for the `structureTensorEigenvalues()` function itself?

BTW, I'm using Mac, and @wolfgangkeil is using Linux.  Apparently this problem is reproducible on both.

**Comment by svenpeter42** [comment]
@stuarteberg thanks for the debugging work, it doesn't look like you are violating any preconditions. I'll take a closer look to figure out what's happening.

**Comment by svenpeter42** [comment]
@stuarteberg didn't we run into this at some point a long time ago? I vaguely remember that I had to change something on my machine but I don't remember what exactly - do you?

`% conda build --python 3.5 --numpy 1.11 fastfilters
Copying /home/speter/phd/software/fastfilters to /home/speter/miniconda3/conda-bld/fastfilters_1493369101718/work
BUILD START: fastfilters-0.2.4.post30-py35_0_g433fd01
updating index in: /home/speter/miniconda3/conda-bld/linux-64
removing: fastfilters-0.2.4.post30-py35_0_g433fd01.tar.bz2
updating index in: /home/speter/miniconda3/conda-bld/noarch

The following NEW packages will be INSTALLED:

    binutils:   2.26-0        ilastik
    cloog:      0.18.0-0             
    gcc:        4.8.5-79991   ilastik
    gmp:        6.1.0-0              
    isl:        0.12.2-0             
    mkl:        2017.0.1-0           
    mpc:        1.0.3-0              
    mpfr:       3.1.5-0              
    numpy:      1.11.3-py35_0        
    openssl:    1.0.2k-1             
    pip:        9.0.1-py35_1         
    python:     3.5.3-1              
    readline:   6.2-2                
    setuptools: 27.2.0-py35_0        
    sqlite:     3.13.0-0             
    tk:         8.5.18-0             
    wheel:      0.29.0-py35_0        
    xz:         5.2.2-1              
    zlib:       1.2.8-3              

ERROR conda.core.link:_execute_actions(335): An error occurred while installing package 'ilastik::gcc-4.8.5-79991'.
LinkError: post-link script failed for package ilastik::gcc-4.8.5-79991
running your command again with `-v` will provide additional information
location of failed script: /home/speter/miniconda3/conda-bld/fastfilters_1493369101718/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/bin/.gcc-post-link.sh
`

**Comment by svenpeter42** [comment]
I had to remove binutils from the deps to get it to build but I'm not able to reproduce the bug. Maybe it was already fixed in the devel branch?

Maybe [e35716d](https://github.com/svenpeter42/fastfilters/commit/e35716d5e384cea3edc268c2965170564749ac0a) fixed it but I forgot to make a new release after that one?

```In [12]: image = np.load('volume-8_17_7_1.npy')

In [13]: image = vigra.taggedView(image, 'zyxc')

In [14]: filtered = fastfilters.structureTensorEigenvalues(image, 1.0, 0.5, 2)

In [15]: np.isnan(filtered).any()

In [16]: fastfilters.__version__
Out[16]: '0.2.4-30-g433fd01'
```

**Comment by stuarteberg** [comment]
>didn't we run into this at some point a long time ago? I vaguely remember that I had to change something on my machine but I don't remember what exactly - do you?

I think you might be referring to this: https://github.com/conda/conda-recipes/pull/691

Anyway, I was able to build the package on Mac, and indeed, the `NaN`s disappear. 

But when I build the package in my Linux VM (and then test it on a real machine), the `NaN`s do not disappear.

```python
>>> import vigra
>>> import numpy as np
>>> import fastfilters
>>> fastfilters.__version__
u'0.2.4-33-gb899b16'
>>> image = np.load('volume-8_17_7_1.npy')
>>> image = vigra.taggedView(image, 'zyxc')
>>> filtered = fastfilters.structureTensorEigenvalues(image, 1.0, 0.5, 2)
>>> np.isnan(filtered).any()
True
```

**Comment by stuarteberg** [comment]
So, just to recap: Building `fastfilters` from the `devel` branch doesn't fix the issue entirely, but it seems to be an improvement (on Mac, at least), so I'll go ahead and use it in the release.

**Comment by svenpeter42** [comment]
I'm still unable to reproduce the bug on my linux machine. Can you upload your build directory with all *.o files, etc. somewhere?

**Comment by stuarteberg** [comment]
>Can you upload your build directory with all *.o files, etc. somewhere?

Here's a copy of the work directory conda used when building the package:

[work.zip](https://github.com/ilastik/ilastik/files/971571/work.zip)

Just to be clear, that was created like this:

```
$ cd /miniconda/conda-bld/fastfilters_1493747612336

$ ls 
_b_env_placehold_placehold_placeh
_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p
prefix_files.txt
work

$ zip -r work work
```

**Comment by svenpeter42** [comment]
That library works just fine on my machines as well.

```(fastfilter-dev) speter@khaos ~/phd/software/fastfilters/build (git)-[devel] 
% python 
Python 3.5.3 |Continuum Analytics, Inc.| (default, Mar  6 2017, 11:58:13) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import fastfilters
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'fastfilters'
>>> 
(fastfilter-dev) speter@khaos ~/phd/software/fastfilters/build (git)-[devel] 
% python wtf.py
Python 3.5.3 |Continuum Analytics, Inc.| (default, Mar  6 2017, 11:58:13) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.0.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import fastfilters

In [2]: import vigra

In [3]: import numpy as np

In [4]: fastfilters.__version__
Out[4]: '0.2.4-35-gf3d6f82'

In [5]: image = np.load('volume-8_17_7_1.npy')

In [6]:  image = vigra.taggedView(image, 'zyxc')

In [7]: filtered = fastfilters.structureTensorEigenvalues(image, 1.0, 0.5, 2)

In [8]: np.isnan(filtered).any()
Out[8]: False

In [9]:                                                                                                                                     
Do you really want to exit ([y]/n)? y

(fastfilter-dev) speter@khaos ~/phd/software/fastfilters/build (git)-[devel] 
% cat wtf.py 
import sys, os, re

if len(sys.argv) == 3:
    outdir = '/' + sys.argv[-1]
else:
    outdir = ''

fastfilters_dir = re.sub('/Release$', outdir, r'/home/speter/phd/software/fastfilters/build')

os.environ.setdefault('LD_LIBRARY_PATH', '')
os.environ.setdefault('PATH', '')

os.environ['PATH'] = os.pathsep.join([fastfilters_dir.replace('/', os.sep), os.environ['PATH']])
os.environ['LD_LIBRARY_PATH'] = os.pathsep.join([fastfilters_dir.replace('/', os.sep), os.environ['LD_LIBRARY_PATH']])
sys.path.insert(0, r'/home/speter/phd/software/fastfilters/build/python')

import IPython as ip
ip.embed()
(fastfilter-dev) speter@khaos ~/phd/software/fastfilters/build (git)-[devel] 
% ls -lah
total 5.1M
[...]
-rwxr-xr-x  1 speter MultBild 672K May  3 09:43 core.cpython-35m-x86_64-linux-gnu.so
[...]
lrwxrwxrwx  1 speter MultBild   78 May  3 09:41 libfastfilters.so -> /home/speter/phd/software/fastfilters/debug/work/build_conda/libfastfilters.so
lrwxrwxrwx  1 speter MultBild   78 May  3 09:43 libfastfilters.so.0.2.4-35-gf3d6f82 -> /home/speter/phd/software/fastfilters/debug/work/build_conda/libfastfilters.so
-rw-r--r--  1 speter MultBild  596 May  3 09:45 wtf.py
[...]
(fastfilter-dev) speter@khaos ~/phd/software/fastfilters/build (git)-[devel] 
% shasum /home/speter/phd/software/fastfilters/debug/work/build_conda/libfastfilters.so 
c44c6a7ae4886d4cf67fde516db01cd4e9b99daa  /home/speter/phd/software/fastfilters/debug/work/build_conda/libfastfilters.so
(fastfilter-dev) speter@khaos ~/phd/software/fastfilters/build (git)-[devel] 
% ldd core.cpython-35m-x86_64-linux-gnu.so 
	linux-vdso.so.1 =>  (0x00007ffe02a94000)
	libfastfilters.so.0.2.4-35-gf3d6f82 => /home/speter/phd/software/fastfilters/build/libfastfilters.so.0.2.4-35-gf3d6f82 (0x00007f9482571000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f94821b7000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f9481fa1000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f9481bd8000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f94818cf000)
	/lib64/ld-linux-x86-64.so.2 (0x00005561582ed000)
```

**Comment by svenpeter42** [comment]
maybe fixed in the latest devel - can you give it a try if you have time @stuarteberg ?

**Comment by chaubold** [comment]
Sven's latest development branch is available as `fastfilters` package in our `ilastik-forge` channel already

**Comment by svenpeter42** [comment]
Does that one already include the two commits from today?

**Comment by chaubold** [comment]
Oh, no it doesnt. Didn't see those yet. Let me know if I should rebuild them.

**Comment by svenpeter42** [comment]
I'm not sure they even work - they might fix this issue which only reliably happened on stuart's computer.

**Comment by k-dominik** [comment]
I think we can consider this one fixed - not a single report about this in 5 years...

**Comment by a-belykh** [comment]
Hi!

I think I have the same issue.

I'm using ilastik-1.4.0-gpu on Windows 10.

I recently added a few .tif images + .h5 probabilities files to my Boundary-based Segmentation with Multicut project. I made some annotations and clicked the "Update Now" button that resulted in an error:

```
RuntimeError

Precondition violation!
RandomForest(): Feature matrix contains NaNs
(d:\bld\vigra_1659002732746\work\include\vigra\random_forest/
rf_preprocessing.hxx:182)
```

If I try to click the "Update Now" button on any other image I have previously annotated in this project (≈40) - I see the same error (although before they were annotated without problems).  .h5 probabilities files were created with the ilastik Object classification tool.
