### ISSUE TITLE
Ilastik 1.4.0b13 Voxel Segmentation, TypeError: No matching signature found

### ISSUE THREAD

**Issue by JMorzy** [ilastik/ilastik#2394]
## Describe the bug
The bug essentially comes down to the voxel classification being unuseable for me. I know it is a beta functionality, but I'd be really interested in giving it a go.

## Expected behavior
I wanted to start labelling and training the voxel classification algorithms, but it throws out an error when doing anything beyond loading the data. Other functionalities work fine. Any ideas on how to approach fixing this would be welcome, especially that I didn't find anything useful that could help by googling. Thanks!

## To Reproduce
1. Fresh ilasik 1.4.0b13 installation on a Win10 with pre-installed Python (not sure if it matters, but most libraries are up to date, including scikit-image which seems to be causing some issues).

## Error message/traceback
After selecting 'feature selection' or 'SLIC applet' I get an error message:
TypeError: No matching signature found slic skimage
I'm attaching the logs here:
[log.txt](https://github.com/ilastik/ilastik/files/5974897/log.txt)

## Desktop (please complete the following information):
 - ilastik version: 1.4.0.b13
 - OS: Windows 10

**Comment by vadmus** [comment]
Hi there!
I got this error both on Windows 10 and Ubuntu machines in ilastik 1.4.0b20 (beta).
I tried to process different image formats (.h5, .tiff (8bit), .tiff (16bit), .jpg) using Voxel segmentation Workflow. This error reproduced using .h5 image format (and perhaps .jpg format), so i resave initial dm4 image in 8bit and 16bit tiff. Using these image formats i didn't reproduce the error

**Comment by tfmertens** [comment]
Hi there,
I'm experiencing the same problem, 'TypeError: No matching signature found' when trying to use the workflow voxel segmentation. I'm using a hdf5 image stack that works with the other workflows seamlessly, so I don't get where the problem lies...
I'd be happy to hear from you if you have any suggestions on how to solve this issue.
I'm excited to start the segmentation in our 3d light sheet microscopy data.

Thank you!

**Comment by louiseAB97** [comment]
Im on MacOS also experiencing this error. I wanna add something though: When i loaded a tiff file I could move on through to the point of feature selection. It only froze after clicking un Live update. When I checked the log in my terminal I discovered the issue might be due to not using the HFD format. So I converted my tiff to hfd and then I was not able to do anything except from loading the data and having the TypeError: No matching signature found

**Comment by vadmus** [comment]
@tfmertens Is it possible to use another file format, like tif?

I think this is due to beta version of program. Maybe this bug is fixed in new beta version - 1.4.0b21

**Comment by louiseAB97** [comment]
I just downloaded the latest beta version and the problem persisted
